# Fly.io deployment configuration for Snake Game
app = "snake-game"
primary_region = "dfw"

[build]
  dockerfile = "dockerfile"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  GAME_SPEED = "150"
  BOARD_SIZE = "20"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"